### ISSUE TITLE
Inconsistent use of OSS/FOSS in the slides

### ISSUE THREAD

**Issue by silverhook** [OpenChain-Project/curriculum#1]
In `slides/openchain-curriculum-for-1-1.*` I found a few inconsistencies in the slides regarding the use of FOSS and OSS.

The biggest issue is on slide 13, where it says (emphasis mine):

> • One popular set of licenses are those approved by the **FOSS Initiative (OSI)**
based on their **FOSS Definition (OSD)**. A complete list of OSI-approved
licenses is available at http://www.opensource.org/licenses/

…which is obviously wrong and should be fixed to “Open Source Initiative” and “Open Source Definition” respectively. It does makes me believe this is just a little bug caused by a simple `s/Open Source/FOSS` search-and-replace.

Another similar issue, where the wording needs to be changed to “FOSS components” (problem emphasised in bold):

slide 53:

> • Compliance management is a set of actions that manages **OSS components**
used in products. Companies may have similar processes in place for
proprietary components. FOSS components are called "Supplied Software" in
the OpenChain specification.

**Comment by shanecoughlan** [comment]
Hi Matija!

Thanks for reporting. I have also added the OpenChain Curriculum mailing list for reference.

Regards

Shane

**Comment by silverhook** [comment]
Thanks @zvr 👍
