### ISSUE TITLE
Wrong scanner name and link of slide 47

### ISSUE THREAD

**Issue by OliverFendt** [OpenChain-Project/curriculum#15]
On slide 47 the last bullet point states:
"A good example of freely available source code scanning tool is Open
Sourceology, a project hosted by the Linux Foundation:
https://www.Open Sourceology.org"

It should be:

"A good example of freely available source code scanning tool is FOSSology, a project hosted by the Linux Foundation:
https://www.FOSSology.org"

**Comment by zvr** [comment]
:rofl: 
I assume a global replace of `FOSS` with `Open Source` produced that.
Thanks, Oliver.
